{"name": "Неуспешное обновление данных пользователя без авторизации - возвращается ожидаемый статус 401", "status": "passed", "parameters": [{"name": "data_field", "value": "'email'"}], "start": 1748983315296, "stop": 1748983315494, "uuid": "ce53d785-7c3f-4227-aa59-35deaf905691", "historyId": "7109b9d87fc62ab327255f13f0d25f69", "testCaseId": "448204f25e08fe008a9484fb13623fc6", "fullName": "tests.test_edit_user.TestEditUser#test_update_user_without_auth_status_401", "labels": [{"name": "feature", "value": "Изменение данных пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_edit_user"}, {"name": "subSuite", "value": "TestEditUser"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_edit_user"}]}