{"name": "Неуспешный логин с неверными учетными данными - возвращается ожидаемый статус 401", "status": "passed", "parameters": [{"name": "wrong_field", "value": "'email'"}], "start": 1748983336940, "stop": 1748983337129, "uuid": "4ccbab8b-5f2b-416c-a967-d74048cd58a2", "historyId": "adeac72a941521d1de429f1cff7cc7cf", "testCaseId": "ba27ddf5800cd265d6623d4203d8af65", "fullName": "tests.test_user_login.TestUserLogin#test_login_invalid_credentials_status_401", "labels": [{"name": "feature", "value": "Логин пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}