{"name": "Успешное получение заказов с авторизацией - в ответе есть 'orders'", "status": "passed", "start": 1748983318150, "stop": 1748983318774, "uuid": "509bcec0-1954-476a-a164-28c9f381077b", "historyId": "befd18ffbec8e1670ae84da2358bd099", "testCaseId": "befd18ffbec8e1670ae84da2358bd099", "fullName": "tests.test_get_orders.TestGetOrdersWithAuth#test_get_orders_with_auth_has_orders", "labels": [{"name": "feature", "value": "Получение заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrdersWithAuth"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}