{"name": "Неуспешное обновление данных пользователя без авторизации - возвращается сообщение о не авторизированном сообщении", "status": "passed", "parameters": [{"name": "data_field", "value": "'name'"}], "start": 1748983315901, "stop": 1748983316107, "uuid": "629de32c-4d2d-4588-a6ee-e8a05a39ac75", "historyId": "f84ca4cd3b087500c8c39d616eb16211", "testCaseId": "15fdf09852331402c6d1f52fa6b17097", "fullName": "tests.test_edit_user.TestEditUser#test_update_user_without_auth_message", "labels": [{"name": "feature", "value": "Изменение данных пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_edit_user"}, {"name": "subSuite", "value": "TestEditUser"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_edit_user"}]}